---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - deployments.deployment-orchestrator.io
  resources:
  - components
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - deployments.deployment-orchestrator.io
  resources:
  - components/finalizers
  verbs:
  - update
- apiGroups:
  - deployments.deployment-orchestrator.io
  resources:
  - components/status
  verbs:
  - get
  - patch
  - update
