---
# Example: WordPress credentials with cross-component reference
apiVersion: deployment-orchestrator.io/v1alpha1
kind: Component
metadata:
  name: wordpress-credentials
  namespace: default
spec:
  handler: secret-push
  dependsOn:
    - wordpress-rds  # Need database endpoint
  config:
    # AWS Secrets Manager configuration
    region: us-east-1
    secretName: "wordpress-demo/admin-credentials"
    kmsKeyId: "alias/wordpress-secrets"  # Optional: custom KMS key
    
    # Field definitions - each has EITHER value OR generator
    fields:
      # Static fields (support cross-component references)
      admin_username:
        value: "admin"
      
      admin_email:
        value: "admin@example.com"
      
      db_host:
        value: "{{ .wordpress_rds.providerStatus.endpoint }}"
      
      db_port:
        value: "{{ .wordpress_rds.providerStatus.port }}"
      
      db_name:
        value: "wordpress"
      
      db_user:
        value: "wpadmin"
      
      # Generated fields (AWS GetRandomPassword)
      admin_password:
        generator:
          passwordLength: 32
          requireEachIncludedType: true
          excludePunctuation: false
      
      api_token:
        generator:
          passwordLength: 64
          excludePunctuation: true
    
    # Policies
    updatePolicy: IfNotExists  # Don't regenerate if secret exists
    deletionPolicy: Delete     # Delete from AWS SM on Component deletion

---
# External Secrets Operator pulls the secret and templates structure
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: wordpress-admin-credentials
  namespace: wordpress
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: wordpress-admin-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # WordPress chart expects these keys
        wordpress-username: "{{ .admin_username }}"
        wordpress-password: "{{ .admin_password }}"
        wordpress-email: "{{ .admin_email }}"
        
        # Database connection string
        database-config: |
          {
            "host": "{{ .db_host }}",
            "port": {{ .db_port }},
            "user": "{{ .db_user }}",
            "database": "{{ .db_name }}"
          }
  dataFrom:
    - extract:
        # Reference the secret path from Component status
        key: "wordpress-demo/admin-credentials"
